const CELESTIAL_CATALOG = [
  {
    id: "sol",
    name: "Earth & Solar System",
    tag: "Solar Reference",
    dataClass: "reference",
    distLy: 0.0,
    distUnc: "—",
    ra: 0,
    dec: 0,
    raText: "00 00 00.000",
    decText: "+00 00 00.00",
    type: "Observer origin / G2V host star",
    desc: "The Solar System defines the observer-centered origin of this atlas. Catalog directions and radial distances are transformed into display coordinates from this reference point.",
    color: "#fffae0",
    size: 5,
    zObs: null,
    rv: null,
    source: "Reference origin",
    record: "Sol-centered coordinate origin",
    sourceRef: "Definition",
    sourceUrl: "",
    distanceBasis: "Defined as 0 ly.",
  },
  {
    id: "proxima",
    name: "Proxima Centauri",
    tag: "Nearby Star — Catalog Record",
    dataClass: "observational",
    distLy: 4.246455222,
    distUnc: "≈ ±0.0003 ly (formal parallax only)",
    ra: 217.428942222,
    dec: -62.6794901891,
    raText: "14 29 42.946133",
    decText: "−62 40 46.164681",
    type: "High proper-motion M-dwarf / Alpha Centauri component",
    desc: "The nearest known star to the Sun. Position, proper motion and parallax in this build are transcribed from the SIMBAD record, whose astrometry cites Gaia EDR3.",
    color: "#ff9d5c",
    size: 3.7,
    zObs: -6.9e-5,
    rv: -20.578199,
    source: "SIMBAD/CDS",
    record:
      "Parallax 768.0665 ± 0.0499 mas; μRA −3781.741 mas/yr; μDec +769.465 mas/yr",
    sourceRef: "2020yCat.1350....0G / 2020AJ....160..120J",
    sourceUrl:
      "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Proxima+Centauri",
    distanceBasis:
      "Direct inverse-parallax visualization distance; formal measurement uncertainty only.",
  },
  {
    id: "sirius",
    name: "Sirius A / B",
    tag: "Binary Star — Catalog Record",
    dataClass: "observational",
    distLy: 8.60093352,
    distUnc: "≈ ±0.04 ly (formal parallax)",
    ra: 101.287155333,
    dec: -16.7161158611,
    raText: "06 45 08.91728",
    decText: "−16 42 58.0171",
    type: "Spectroscopic binary; A-type primary + white dwarf",
    desc: "The brightest star system in Earth’s night sky. The position, proper motion, parallax and radial velocity shown here are catalog measurements surfaced through SIMBAD.",
    color: "#d4e6ff",
    size: 4.2,
    zObs: -1.8e-5,
    rv: -5.5,
    source: "SIMBAD/CDS",
    record:
      "Parallax 379.21 ± 1.58 mas; μRA −546.01 mas/yr; μDec −1223.07 mas/yr",
    sourceRef: "2007A&A...474..653V; 2006AstL...32..759G",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Sirius",
    distanceBasis: "Direct inverse-parallax visualization distance.",
  },
  {
    id: "vega",
    name: "Vega (Alpha Lyrae)",
    tag: "Reference Star — Catalog Record",
    dataClass: "observational",
    distLy: 25.044613376,
    distUnc: "≈ ±0.07 ly (formal parallax)",
    ra: 279.234734792,
    dec: 38.7836889444,
    raText: "18 36 56.33635",
    decText: "+38 47 01.2802",
    type: "A0V star",
    desc: "A bright A-type standard star. SIMBAD lists the ICRS position, proper motion, parallax and radial velocity used in this embedded record.",
    color: "#99c5ff",
    size: 3.8,
    zObs: -4.5e-5,
    rv: -13.5,
    source: "SIMBAD/CDS",
    record:
      "Parallax 130.23 ± 0.36 mas; μRA +200.94 mas/yr; μDec +286.23 mas/yr",
    sourceRef: "2007A&A...474..653V; 2004A&A...420..183A",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Vega",
    distanceBasis: "Direct inverse-parallax visualization distance.",
  },
  {
    id: "arcturus",
    name: "Arcturus (Alpha Boötis)",
    tag: "Red Giant — Catalog Record",
    dataClass: "observational",
    distLy: 36.71687493,
    distUnc: "≈ ±0.22 ly (formal parallax)",
    ra: 213.915300292,
    dec: 19.1824091667,
    raText: "14 15 39.67207",
    decText: "+19 10 56.6730",
    type: "K1.5III giant",
    desc: "A nearby orange giant with high proper motion. Astrometry and radial velocity are embedded from the SIMBAD record and its cited literature.",
    color: "#ffaa44",
    size: 4,
    zObs: -1.7e-5,
    rv: -5.229,
    source: "SIMBAD/CDS",
    record:
      "Parallax 88.83 ± 0.54 mas; μRA −1093.39 mas/yr; μDec −2000.06 mas/yr",
    sourceRef: "2007A&A...474..653V; 2018A&A...616A...7S",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Arcturus",
    distanceBasis: "Direct inverse-parallax visualization distance.",
  },
  {
    id: "pleiades",
    name: "Pleiades Cluster (M45)",
    tag: "Open Cluster — Catalog Record",
    dataClass: "observational",
    distLy: 442.906029332,
    distUnc: "≈ ±0.3 ly (formal mean parallax)",
    ra: 56.6008333333,
    dec: 24.1138888889,
    raText: "03 46 24.2",
    decText: "+24 06 50",
    type: "Open cluster",
    desc: "The Pleiades open cluster. The embedded SIMBAD record reports a mean parallax of 7.364 mas and proper motion values from Gaia-era cluster astrometry.",
    color: "#77b3ff",
    size: 4.6,
    zObs: 2e-5,
    rv: 5.88,
    source: "SIMBAD/CDS",
    record:
      "Mean parallax 7.364 ± 0.005 mas; μRA +19.997 mas/yr; μDec −45.548 mas/yr",
    sourceRef: "2018A&A...616A..10G; 2021A&A...647A..19T",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=M45",
    distanceBasis:
      "Inverse of the catalog mean parallax for atlas visualization; cluster depth is not represented.",
  },
  {
    id: "betelgeuse",
    measurementEligible: false,
    name: "Betelgeuse (Alpha Orionis)",
    tag: "Red Supergiant — Catalog Record",
    dataClass: "observational",
    distLy: 497.948091603,
    distUnc: "≈ ±63 ly (formal parallax; systematics important)",
    ra: 88.792939,
    dec: 7.407064,
    raText: "05 55 10.30536",
    decText: "+07 24 25.4304",
    type: "M1–M2 Ia–Iab red supergiant",
    desc: "Legacy inverse-parallax display distance retained from v4. Later seismic and radio estimates differ substantially (Joyce 2020; Harper 2017). Excluded from physical separation; this is not a consensus precision distance.",
    color: "#ff4433",
    size: 4.8,
    zObs: 7.3e-5,
    rv: 21.91,
    source: "SIMBAD/CDS",
    record: "Parallax 6.55 ± 0.83 mas; μRA +27.54 mas/yr; μDec +11.30 mas/yr",
    sourceRef: "2007A&A...474..653V; 2005A&A...430..165F",
    sourceUrl:
      "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Betelgeuse",
    distanceBasis:
      "Naive inverse-parallax display distance; uncertainty/systematics are scientifically significant.",
  },
  {
    id: "orion_nebula",
    name: "Orion Nebula (M42)",
    tag: "H II Region — Catalog + Literature",
    dataClass: "observational",
    distLy: 1350.28584,
    distUnc: "±23 ly (±7 pc)",
    ra: 83.82,
    dec: -5.3875,
    raText: "05 35 16.8",
    decText: "−05 23 15",
    type: "H II region / stellar nursery",
    desc: "The Orion Nebula / Orion Nebula Cluster region. The sky position is from SIMBAD; the adopted distance is a published VLBA trigonometric-parallax result.",
    color: "#ff77a8",
    size: 5,
    zObs: null,
    rv: null,
    source: "SIMBAD/CDS + Menten et al. (2007)",
    record: "SIMBAD object M 42; adopted ONC distance 414 ± 7 pc",
    sourceRef: "2022A&A...661A..38P; 2007A&A...474..515M",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-id?Ident=Orion+Nebula",
    distanceBasis:
      "Literature trigonometric-parallax distance to the Orion Nebula Cluster.",
    distanceUrl: "https://arxiv.org/abs/0709.0485",
  },
  {
    id: "sgra",
    name: "Sagittarius A* (Galactic Centre)",
    tag: "SMBH — Catalog + Geometric Distance",
    dataClass: "observational",
    distLy: 26673.03768,
    distUnc: "≈ ±83 ly combined statistical/systematic",
    ra: 266.416816625,
    dec: -29.0078249722,
    raText: "17 45 40.03599",
    decText: "−29 00 28.1699",
    type: "Galactic-centre supermassive black hole",
    desc: "The compact radio source associated with the Milky Way’s central black hole. Position is from SIMBAD; distance uses the GRAVITY Collaboration geometric S2-orbit measurement.",
    color: "#ffbe3b",
    size: 6.2,
    zObs: null,
    rv: null,
    source: "SIMBAD/CDS + GRAVITY Collaboration",
    record: "Sgr A* ICRS radio position; R0 = 8178 ± 13(stat) ± 22(sys) pc",
    sourceRef: "2011AJ....142...35P; 2019A&A...625L..10G",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=sgr+A",
    distanceBasis: "Geometric Galactic-centre distance from the S2 orbit.",
    distanceUrl: "https://arxiv.org/abs/1904.05721",
  },
  {
    id: "lmc",
    name: "Large Magellanic Cloud (LMC)",
    tag: "Satellite Galaxy — Catalog + Geometric Distance",
    dataClass: "observational",
    distLy: 161740.7604,
    distUnc: "±1.8 kly (systematic-dominated)",
    ra: 80.8941666667,
    dec: -69.7561111111,
    raText: "05 23 34.6",
    decText: "−69 45 22",
    type: "Magellanic irregular satellite galaxy",
    desc: "A major Milky Way satellite and a cornerstone of the extragalactic distance ladder. Position and redshift are from SIMBAD; distance uses late-type eclipsing binaries.",
    color: "#b0c8f0",
    size: 6.5,
    zObs: 0.000875,
    rv: 262.2,
    source: "SIMBAD/CDS + Pietrzyński et al. (2019)",
    record:
      "LMC catalog position; geometric distance 49.59 ± 0.09(stat) ± 0.54(sys) kpc",
    sourceRef: "2003A&A...412...45P; Nature 567, 200–203 (2019)",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=LMC",
    distanceBasis:
      "Eclipsing-binary geometric distance; preferred over using local peculiar redshift.",
    distanceUrl: "https://www.nature.com/articles/s41586-019-0999-4",
  },
  {
    id: "andromeda",
    name: "Andromeda Galaxy (M31)",
    tag: "Local Group Galaxy — Catalog + Literature",
    dataClass: "observational",
    distLy: 2553801.48,
    distUnc: "≈ ±82 kly (±25 kpc adopted)",
    ra: 10.6847083333,
    dec: 41.26875,
    raText: "00 42 44.330",
    decText: "+41 16 07.50",
    type: "SA(s)b spiral galaxy",
    desc: "The dominant large galaxy of the Local Group alongside the Milky Way. The ICRS position and heliocentric redshift are from SIMBAD; a literature distance is adopted because peculiar velocity dominates locally.",
    color: "#d0e4ff",
    size: 7.5,
    zObs: -0.001,
    rv: -300,
    source: "SIMBAD/CDS + Local Group literature",
    record: "M 31 / NGC 224; radial velocity −300 ± 4 km/s",
    sourceRef: "2006AJ....131.1163S; McConnachie (2012)",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=M31",
    distanceBasis:
      "Adopted heliocentric Local Group distance 783 ± 25 kpc; redshift is not used as a Hubble-flow distance.",
    distanceUrl: "https://arxiv.org/abs/1204.1562",
  },
  {
    id: "triangulum",
    name: "Triangulum Galaxy (M33)",
    tag: "Local Group Galaxy — Catalog + Literature",
    dataClass: "observational",
    distLy: 2638602.04,
    distUnc: "≈ ±78 kly (±24 kpc)",
    ra: 23.4620690622,
    dec: 30.660175112,
    raText: "01 33 50.896575",
    decText: "+30 39 36.630403",
    type: "SA(s)cd spiral galaxy",
    desc: "The third-largest major galaxy of the Local Group. ICRS position and observed redshift come from SIMBAD; distance is a TRGB-based literature value.",
    color: "#a4d4ff",
    size: 5.7,
    zObs: -0.000598,
    rv: -179.2,
    source: "SIMBAD/CDS + McConnachie et al.",
    record: "M 33; observed radial velocity −179.2 ± 1.7 km/s",
    sourceRef: "2020yCat.1350....0G; McConnachie et al. 2004/2005",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=M33",
    distanceBasis:
      "Adopted TRGB distance 809 ± 24 kpc; local peculiar velocity makes redshift unsuitable as a distance proxy.",
    distanceUrl: "https://academic.oup.com/mnras/article/428/2/1248/1002981",
  },
  {
    id: "centaurus_a",
    name: "Centaurus A (NGC 5128)",
    tag: "Active Galaxy — Catalog + Literature",
    dataClass: "observational",
    distLy: 12393928.0,
    distUnc: "±0.33 Mly (±0.1 Mpc)",
    ra: 201.365063377,
    dec: -43.0191125081,
    raText: "13 25 27.615210",
    decText: "−43 01 08.805029",
    type: "Active peculiar elliptical/lenticular radio galaxy",
    desc: "The nearest powerful radio galaxy. SIMBAD supplies the precise radio position and observed redshift; the adopted distance comes from a multi-method distance review.",
    color: "#ff9966",
    size: 6,
    zObs: 0.00187695,
    rv: 562,
    source: "SIMBAD/CDS + Harris, Rejkuba & Harris",
    record: "NGC 5128 / Centaurus A; z = 0.00187695",
    sourceRef: "2020A&A...644A.159C; PASA 27, 457–462 (2010)",
    sourceUrl:
      "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Centaurus+A",
    distanceBasis: "Best-estimate literature distance 3.8 ± 0.1 Mpc.",
    distanceUrl: "https://arxiv.org/abs/0911.3180",
  },
  {
    id: "quasar_3c273",
    name: "3C 273",
    tag: "Quasar — Catalog + Cosmology",
    dataClass: "observational",
    distLy: redshiftToComovingDistance(0.15756751),
    distUnc: "Model-dependent comoving distance",
    ra: 187.27791594,
    dec: 2.05238823055,
    raText: "12 29 06.699826",
    decText: "+02 03 08.597630",
    type: "Quasar / active galactic nucleus",
    desc: "The historically first identified quasar. Its precise ICRS direction and spectroscopic redshift are embedded from SIMBAD; radial distance is derived from that observed redshift under the atlas ΛCDM model.",
    color: "#ffdd44",
    size: 6.7,
    zObs: 0.15756751,
    rv: 43555,
    source: "SIMBAD/CDS + Planck-like ΛCDM conversion",
    record: "3C 273; spectroscopic z = 0.15756751 ± 0.0005",
    sourceRef: "2020yCat.1350....0G; 2022ApJS..261....2K",
    sourceUrl: "https://simbad.cds.unistra.fr/simbad/sim-id?Ident=3C273",
    distanceBasis:
      "Comoving distance numerically derived from observed z using this build’s Planck-2018-like cosmology.",
    distanceUrl: "https://arxiv.org/abs/1807.06209",
  },
  {
    id: "virgo_cluster",
    name: "Virgo Cluster (context centre)",
    tag: "Context Landmark",
    dataClass: "context",
    distLy: 54000000.0,
    distUnc: "Representative scale",
    ra: 186.75,
    dec: 12.72,
    raText: "≈ 12h 27m",
    decText: "≈ +12° 43′",
    type: "Galaxy cluster context marker",
    desc: "Representative center used to navigate the Virgo-region scale. This is a contextual atlas landmark, not a precision centroid or a substitute for member-galaxy catalog data.",
    color: "#66ccff",
    size: 7.5,
    zObs: null,
    rv: null,
    source: "Illustrative context",
    record: "Representative Virgo-region center",
    sourceRef: "Not a single catalog object",
    sourceUrl: "",
    distanceBasis: "Approximate navigation distance.",
  },
  {
    id: "great_attractor",
    name: "Great Attractor region",
    tag: "Context Landmark",
    dataClass: "context",
    distLy: 220000000.0,
    distUnc: "Representative scale",
    ra: 243.8,
    dec: -60.8,
    raText: "≈ 16h 15m",
    decText: "≈ −60° 48′",
    type: "Large-scale flow / gravitational basin context",
    desc: "A navigation marker for the Great Attractor / Norma region. The phenomenon is extended and model-dependent; the point shown here is deliberately labeled as context rather than an observed object.",
    color: "#ff44aa",
    size: 8,
    zObs: null,
    rv: null,
    source: "Illustrative context",
    record: "Representative large-scale-flow landmark",
    sourceRef: "Extended region; no single-point catalog identity",
    sourceUrl: "",
    distanceBasis: "Approximate navigation distance.",
  },
  {
    id: "coma_cluster",
    name: "Coma Cluster (context)",
    tag: "Context Landmark",
    dataClass: "context",
    distLy: 321000000.0,
    distUnc: "Representative scale",
    ra: 194.95,
    dec: 27.98,
    raText: "≈ 12h 59m 48s",
    decText: "≈ +27° 59′",
    type: "Galaxy-cluster context marker",
    desc: "Representative Coma Cluster landmark retained for scale navigation. The point is contextual; individual member galaxies should be used for precision catalog work.",
    color: "#88e0ff",
    size: 7,
    zObs: null,
    rv: null,
    source: "Illustrative context",
    record: "Approximate cluster navigation center",
    sourceRef: "Context layer",
    sourceUrl: "",
    distanceBasis: "Approximate navigation distance.",
  },
  {
    id: "shapley",
    name: "Shapley Supercluster region",
    tag: "Context Landmark",
    dataClass: "context",
    distLy: 650000000.0,
    distUnc: "Representative scale",
    ra: 202.5,
    dec: -31.5,
    raText: "≈ 13h 30m",
    decText: "≈ −31° 30′",
    type: "Supercluster context marker",
    desc: "Representative marker for the Shapley concentration. It is an extended structure and is therefore not represented as a precision point measurement.",
    color: "#ff66cc",
    size: 8,
    zObs: null,
    rv: null,
    source: "Illustrative context",
    record: "Representative supercluster landmark",
    sourceRef: "Context layer",
    sourceUrl: "",
    distanceBasis: "Approximate navigation distance.",
  },
  {
    id: "bootes_void",
    name: "Boötes Void region",
    tag: "Context Landmark",
    dataClass: "context",
    distLy: 700000000.0,
    distUnc: "Representative scale",
    ra: 219,
    dec: 35,
    raText: "≈ 14h 36m",
    decText: "≈ +35°",
    type: "Cosmic-void context marker",
    desc: "A representative point for navigating the Boötes Void scale. The void is spatially extended; this marker is not a physical object at a single coordinate.",
    color: "#223366",
    size: 8.5,
    zObs: null,
    rv: null,
    source: "Illustrative context",
    record: "Representative void-region landmark",
    sourceRef: "Context layer",
    sourceUrl: "",
    distanceBasis: "Approximate navigation distance.",
  },
  {
    id: "sloan_wall",
    name: "Sloan Great Wall region",
    tag: "Context Landmark",
    dataClass: "context",
    distLy: 1200000000.0,
    distUnc: "Representative scale",
    ra: 190,
    dec: 5,
    raText: "≈ 12h 40m",
    decText: "≈ +05°",
    type: "Large-scale structure context marker",
    desc: "A representative navigation point for the Sloan Great Wall scale. The wall is an extended galaxy distribution, not a point source.",
    color: "#00ffbb",
    size: 8.5,
    zObs: null,
    rv: null,
    source: "Illustrative context",
    record: "Representative cosmic-wall landmark",
    sourceRef: "Context layer",
    sourceUrl: "",
    distanceBasis: "Approximate navigation distance.",
  },
  {
    id: "cmb_horizon",
    name: "Cosmic Microwave Background",
    tag: "Cosmology Model Surface",
    dataClass: "model",
    distLy: CMB_DISTANCE_LY,
    distUnc: "Model-derived comoving radius",
    ra: 0,
    dec: 0,
    raText: "All-sky surface",
    decText: "All-sky surface",
    type: "Last-scattering surface (z ≈ 1089)",
    desc: "The last-scattering surface rendered at the model comoving distance corresponding to z ≈ 1089. The sphere texture is procedural and must not be interpreted as Planck sky-map data.",
    color: "#ff3366",
    size: 10,
    zObs: 1089,
    rv: null,
    source: "Planck-like ΛCDM model",
    record: "z ≈ 1089 last-scattering surface",
    sourceRef: "Planck 2018 cosmological parameters",
    sourceUrl: "https://arxiv.org/abs/1807.06209",
    distanceBasis:
      "Numerical comoving distance under the atlas cosmological model.",
  },
];

CELESTIAL_CATALOG.forEach((item) => {
  item.distanceKind =
    item.id === "quasar_3c273" ? "comoving" : "source_adopted";
  item.pos = astronomicalToCartesian(item.ra, item.dec, item.distLy);
});

document.getElementById("model-radius-label").innerText =
  `Scientific v5 • model radius ≈ ${(MODEL_MAX_LY / 1e9).toFixed(2)} Gly • CMB ≈ ${(CMB_DISTANCE_LY / 1e9).toFixed(2)} Gly • observed/context/model tiers`;
