const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({console,assert});
const names=['astronomy/time.js','astronomy/observer.js','astronomy/coordinates.js','astronomy/frames.js','astronomy/time-scales.js','astronomy/ephemeris.js',
  'physics/model.js','physics/gravity.js','physics/integrator.js','physics/diagnostics.js','physics/presets.js','missions/lambert.js',
  'astronomy/measurement.js','catalog/local-pack.js','terrain/model.js'];
// Cone tests use the same independently established stable angular geometry as v5.
vm.runInContext(names.map(n=>fs.readFileSync(path.join(root,'src',n),'utf8')).join('\n'),ctx);
ctx.asset=JSON.parse(fs.readFileSync(path.join(root,'data/ephemeris/solar-system-2026-2027.json'),'utf8'));
ctx.fixture=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/v6-reference.json'),'utf8'));
let count=0;function test(name,source){vm.runInContext('{'+source+'}',ctx);count++;console.log('PASS '+name);}
test('Ephemeris schema, bounds and unsupported scale',`validateEphemerisAsset(asset);assert.throws(()=>ephemerisState(asset,'399',asset.validRangeJd[0]-1));assert.throws(()=>ephemerisState(asset,'399',asset.validRangeJd[1]+1));assert.throws(()=>ephemerisState(asset,'unknown',asset.validRangeJd[0]));assert.throws(()=>validateEphemerisAsset({...asset,timeScale:'UTC'}));assert.throws(()=>validateEphemerisAsset({...asset,cadenceDays:0}));`);
let comparisons=0,maxPositionKm=0,maxVelocityKmS=0;
for(const target of Object.keys(ctx.asset.bodies)){
  const raw=JSON.parse(fs.readFileSync(path.join(root,`data/ephemeris/raw/${target}-midpoints.json`),'utf8')).result;
  const rows=raw.split('$$SOE')[1].split('$$EOE')[0].trim().split('\n').map(line=>{const cols=line.split(',');return [+cols[0],...cols.slice(2,8).map(Number)]});
  ctx.refs=rows;ctx.target=target;
  const report=vm.runInContext(`(()=>{let maxP=0,maxV=0;for(const row of refs){const state=ephemerisState(asset,target,row[0]);maxP=Math.max(maxP,Math.hypot(...state.positionAu.map((v,i)=>v-row[i+1]))*AU_KM);maxV=Math.max(maxV,Math.hypot(...state.velocityAuDay.map((v,i)=>v-row[i+4]))*AU_KM/86400);}assert.ok(maxP<1);assert.ok(maxV<0.0001);return {maxP,maxV};})()`,ctx);
  comparisons+=rows.length;maxPositionKm=Math.max(maxPositionKm,report.maxP);maxVelocityKmS=Math.max(maxVelocityKmS,report.maxV);
}
test('Exact samples and terminal endpoint retain source category',`for(const jd of [asset.validRangeJd[0],asset.validRangeJd[1]]){const s=ephemerisState(asset,'399',jd);const samples=asset.bodies['399'].samples,r=jd===asset.validRangeJd[0]?samples[0]:samples.at(-1);assert.ok(Math.hypot(...s.positionAu.map((x,i)=>x-r[i+1]))<1e-14);assert.ok(s.provenance.category.includes('sampled'));}`);
test('Heliocentric and geocentric state subtraction',`const jd=asset.validRangeJd[0]+.125,e=ephemerisState(asset,'399',jd),sun=ephemerisState(asset,'10',jd),h=ephemerisState(asset,'399',jd,'10');assert.ok(Math.hypot(...h.positionAu.map((x,i)=>x-e.positionAu[i]+sun.positionAu[i]))<1e-16);assert.equal(Math.hypot(...ephemerisState(asset,'399',jd,'399').positionAu),0);assert.throws(()=>geometricDirectionFromState(ephemerisState(asset,'399',jd,'399')));`);
test('Conventional ICRF directions do not use renderer axis order',`const d=geometricDirectionFromState({positionAu:[0,1,0],frame:'ICRF',epochJd:1,timeScale:'TDB',provenance:{}});assert.equal(d.raDeg,90);assert.equal(d.decDeg,0);`);
test('Independent ERFA UTC→TT and approximate geocentric TDB',`for(const r of fixture.time){const t=utcToTimeScales(r.utc,37);assert.ok(Math.abs(t.jdTt-r.jdTt)<1e-9);assert.ok(Math.abs(t.jdTdb-r.jdTdbErfa)*86400<0.00015);}`);
test('Mean sidereal algorithm independently checked against ERFA gmst82',`for(const r of fixture.sidereal)assert.ok(Math.abs(greenwichMeanSiderealDeg(r.jdUt1)-r.gmstDeg)<3e-7);assert.equal(icrsToHorizontalApprox(0,91,2451545,{latitudeDeg:0,longitudeDeg:0}),null);`);
test('Time rejects missing offset, local dates, calendar normalization and unsupported era',`for(const iso of ['1950-01-01T00:00:00Z','2026-02-30T00:00:00Z','2026-09-30T00:00:60Z','2026-09-30','2200-01-01T00:00:00Z'])assert.throws(()=>utcToTimeScales(iso,37));assert.throws(()=>utcToTimeScales('2026-09-30T00:00:00Z',undefined));`);
test('Lambert analytical circular quarter orbit, both arc choices',`const a=solveLambert([1,0,0],[0,1,0],Math.PI/2,1);assert.ok(Math.hypot(a.departureVelocity[0],a.departureVelocity[1]-1,a.departureVelocity[2])<1e-10);assert.ok(Math.hypot(a.arrivalVelocity[0]+1,a.arrivalVelocity[1],a.arrivalVelocity[2])<1e-10);const b=solveLambert([1,0,0],[0,1,0],3*Math.PI/2,1,{longWay:true});assert.ok(Math.hypot(b.departureVelocity[0],b.departureVelocity[1]+1,b.departureVelocity[2])<1e-10);`);
test('Published CelesTrak Vallado zero-revolution long-way case',`const r=fixture.lambert,c=solveLambert(r.r1Km,r.r2Km,r.seconds,r.muKm3S2,{longWay:true});assert.ok(Math.hypot(...c.departureVelocity.map((v,i)=>v-r.departureKmS[i]))<2e-7);assert.ok(Math.hypot(...c.arrivalVelocity.map((v,i)=>v-r.arrivalKmS[i]))<2e-7);`);
test('Lambert malformed/singular/bounded inputs',`for(const [a,b,t,mu] of [[[0,0,0],[1,0,0],1,1],[[1,0,0],[-1,0,0],1,1],[[1,0,0],[0,1,0],0,1],[[1,0,0],[0,1,0],1,NaN],[[1,0],[0,1,0],1,1]])assert.throws(()=>solveLambert(a,b,t,mu));`);
test('Hyperbolic transfer independently propagated by RK4',`const time=.1,sol=solveLambert([1,0,0],[0,1,0],time,1);let s=[1,0,0,...sol.departureVelocity];const dt=time/4000;const rhs=x=>{const r=Math.hypot(...x.slice(0,3));return [...x.slice(3),...x.slice(0,3).map(v=>-v/r**3)];};const add=(a,b,t)=>a.map((v,i)=>v+b[i]*t);for(let i=0;i<4000;i++){const k1=rhs(s),k2=rhs(add(s,k1,dt/2)),k3=rhs(add(s,k2,dt/2)),k4=rhs(add(s,k3,dt));s=s.map((v,j)=>v+dt*(k1[j]+2*k2[j]+2*k3[j]+k4[j])/6);}assert.ok(Math.hypot(s[0],s[1]-1,s[2])<1e-7);`);
test('Mission metrics derive from source states and enforce epoch range',`const m=missionFromEphemeris(asset,'399','4',2461131.5,2461381.5);assert.ok(m.c3Km2S2>=0);assert.ok(Math.abs(m.c3Km2S2-m.departureVInfinityKmS**2)<1e-10);assert.equal(m.departure.timeScale,'TDB');assert.throws(()=>missionFromEphemeris(asset,'399','4',2461131.5,asset.validRangeJd[1]+1));`);
test('Verlet step count and malformed input refusal',`let s=simulationFromPreset('binary-star',{stepDays:.5});s=advanceSimulation(s,2);assert.equal(s.steps,4);assert.equal(cloneSimulationState(s).steps,4);assert.throws(()=>advanceSimulation(s,100,2));assert.throws(()=>advanceSimulation(s,NaN));assert.throws(()=>createSimulationState([{id:'bad',massSolar:0}]));const b={id:'a',massSolar:1,positionAu:[0,0,0],velocityAuDay:[0,0,0]};assert.throws(()=>velocityVerletStep(createSimulationState([b,{...b,id:'b'}])));`);
test('Verlet second-order convergence against analytical equal-mass binary',`const omega=Math.sqrt(2*GRAVITATIONAL_CONSTANT_AU3_SOLAR_MASS_DAY2),duration=80,errors=[];for(const dt of [2,1,.5]){const initial=simulationFromPreset('binary-star',{stepDays:dt}),s=advanceSimulation(initial,duration),expected=[.5*Math.cos(omega*duration),.5*Math.sin(omega*duration),0];errors.push(Math.hypot(...subtractVec3(s.bodies[1].positionAu,expected)));const q=simulationQuality(s,simulationDiagnostics(initial),initial.timeJd);assert.ok(q.angularMomentumRelativeDrift<1e-12);assert.ok(q.centerOfMassResidualAu<1e-12);assert.ok(q.momentumAbsoluteDrift<1e-12);}assert.ok(errors[0]/errors[1]>3.8&&errors[1]/errors[2]>3.8);console.log('CONVERGENCE '+JSON.stringify(errors));`);
test('Local manifest rejects fake indexing, paths, duplicate and count mismatch',`const m=fixture.pack;validateLocalPack(m);assert.throws(()=>validateLocalPack({...m,scheme:'HEALPix NESTED'}));assert.throws(()=>validateLocalPack({...m,recordCount:2}));assert.throws(()=>validateLocalPack({...m,tiles:[{...m.tiles[0],file:'../tile'}]}));assert.throws(()=>validateLocalPack({...m,tiles:[m.tiles[0],m.tiles[0]]}));`);
test('Conservative source-cap cone intersection, RA wrap and poles',`const m=fixture.pack;assert.equal(localPackTilesForCone(m,359,0,2).length,1);assert.equal(localPackTilesForCone(m,180,0,2).length,0);assert.throws(()=>localPackTilesForCone(m,0,91,1));`);
test('Terrain remains metadata-only and rejects missing provenance, invalid latitude and NaN height',`assert.equal(validateTerrainAsset({schema:'cosmic-atlas.terrain-asset.v1'}),null);const a={schema:'cosmic-atlas.terrain-asset.v1',source:'external reference',body:'Moon',projection:'equirectangular',datum:'declared reference sphere',retrievedAt:'2026-09-30T00:00:00Z',license:'source-specific',licenseUrl:'https://example.org/terms',sha256:'a'.repeat(64),resolutionMeters:100,noDataPolicy:'mask',redistributionReviewed:true};assert.ok(validateTerrainAsset(a).status.includes('not implemented'));const b={id:'earth',equatorialRadiusKm:6378};assert.equal(terrainEllipsoidPoint(b,91,0,0),null);assert.equal(terrainEllipsoidPoint(b,0,0,NaN),null);`);
const result={passed:count,horizonsHeldoutComparisons:comparisons,maxPositionErrorKm:maxPositionKm,maxVelocityErrorKmS:maxVelocityKmS};
fs.mkdirSync(path.join(root,'qa/v6'),{recursive:true});fs.writeFileSync(path.join(root,'qa/v6/numerics.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
